### ISSUE TITLE
Use a newer eslint version

### ISSUE THREAD

**Issue by siebertm** [prontolabs/pronto-eslint#9]
Currently, `pronto-eslint` is using [zendesk/eslintrb](https://github.com/zendesk/eslintrb) which itself bundles eslint v2.7.0.

Newer eslint versions have newer features, so being able to using these would be very good.

I already created a MR to update the bundled eslint version but it's not yet merged (zendesk/eslintrb#9)

As soon as this is merged, we should incorporate this here, too!

**Comment by mmozuras** [comment]
@siebertm no change should be required on `pronto-eslint` side 😄 

Here's how the dependency is defined:

`s.add_dependency('eslintrb', '~> 2.0', '>= 2.0.0')`

Current `eslintrb` version is `2.1.0`. I expect that the version will be bumped to `2.2.0`, which won't require any changes here. That's why I'm closing this issue. Please reopen, if I missed anything or the version will get bumped to `3.0.0` 😄
